### ISSUE TITLE
Documentation lacking for real-world err handling

### ISSUE THREAD

**Issue by drauschenbach** [jprichardson/node-nextflow#1]
Real examples are lacking for err arg handling. Tests perform I/O operations outside of a flow, which doesn't help. Providing an equivalent of the "seq" module's stat_all.js (or stat_all.coffee in this case) would make everything clear.

FWIW, the "seq" module's ".catch" feature is hard to beat.

**Comment by jprichardson** [comment]
Excellent point. I'll have to look into this a bit more.

**Comment by jprichardson** [comment]
I've updated the documentation to reflect error handling. I'll see if I can add an equivalent to `stat_all.js` from `seq`.

**Comment by jprichardson** [comment]
OK, regarding a stat_all example, I really don't think `nextflow` is a viable substitute in this case. This is because `nextflow` lacks an equivalent `parForEach()` method and it probably won't have one anytime soon. `async`, `seq`, and `step` are very powerful, but they contain too much. `nextflow` does one thing, and IMHO it does that one thing well. Thanks for posting this though, as I've thought a lot about all of this.

But, as stated in my previous post, I did update `nextflow` to contain error handling equivablent to the `.catch` feature in `seq`.
