### ISSUE TITLE
async + coffee

### ISSUE THREAD

**Issue by ichernev** [jprichardson/node-nextflow#2]
There is a better syntax for using async with coffee:

``` coffeescript
async.series [
  (next) ->
    someAsyncFunc arg1, arg2, next
  (next) ->
    anotherAsyncFunc arg1, arg2, next
], (err) ->
  console.log "we're done"
```

``` coffeescript
async.forEach array,
  (elem, next) ->
     console.log elem
     next null
  (err) ->
    console.log 'done'
```

In nextflow, you have to name the next step (equivalent in waterfall), so its not super easy to add new steps in between.

You may update the Readme, because it puts async in a bad light ;-)

**Comment by STRML** [comment]
I rather like the NextFlow syntax in comparison - it better separates elements visually. But I agree, it's an unfair comparison with async.

I do very much like the required naming in NextFlow. Rather than naming your steps by numbers you really should be naming them by what they do. And being able to call steps easily by name is very useful for non-sequential flows, which happen very often in my apps.

**Comment by jprichardson** [comment]
I'm with @STRML on this one.

The naming acts as implicit comments. I've actually started using NextFlow in JavaScript projects as well because of it. See: https://github.com/rocktemplates/rock/blob/master/lib/rock.js for ref.

But, you are both correct about `async` being unfairly placed in a negative light. When I wrote the Readme, I wasn't aware of some of the features behind async. 

I'll update the README to include an updated async comparison and include better examples with context for NextFlow.

**Comment by ichernev** [comment]
Oh, I didn't see you can use `next` instead of explicitly specifying the name. Also I agree the step key servers as documentation, and you may also do a little bit of branching (like implement async `if-else`). So this project has some legitimate uses ;-)

You can achieve consecutive execution with keys (serving as comments) with `async.series`, but you can not pass arguments from one step to the next. For trivial workflow that does the job (either not being able to pass anything or to receive arguments from the previous step), but if things get complicated I just create an object above the flow structure and use it as a bucket for data I may use in several steps (and you can use plain `async.series` for that). 

Off-topic: You may use `for own key, val in sth` in coffee-script instead of `hasOwnProperty` inside the loop.

**Comment by jprichardson** [comment]
Updated the Readme. Let me know if you have any more suggestions. Thanks for chiming in guys. @ichernev Thanks for that CoffeeScript tip, I didn't know that!
